apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-update-secret"
  labels:
    {{- include "alation-helm-chart.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"

rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
