{{- if .Values.secret.enabled }}
{{- range .Values.secret.entries }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s"  .namePrefix  (include "alation-helm-chart.fullname" $) }}
  labels:
    {{- include "alation-helm-chart.labels" $ | nindent 4 }}
data:
  {{-  if .isFile }}
  {{ .filename }}: |-
    {{ b64enc (toJson .data) }}  
  {{- else }}
  {{- range $key, $val := .data }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
