apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-registry
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.alation.com/registry
          operator: In
          values:
          - registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry
  name: registry-pvc
  namespace: kurl
spec:
  volumeName: pv-registry
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  