apiVersion: v1
kind: PersistentVolume
metadata:
  name: %s
spec:
  capacity:
    storage: %s
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: %s
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: %s
          operator: In
          values:
          - %s
