# This is a basic workflow that is manually triggered

name: Context information

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      ALATIONANALYTICS:
        description: 'Alation Analytics(ALATIONANALYTICS) version'
        required: false
      EXCLUDE_MODULES:
        description: 'List of comma separated modules to be excluded(ex: ALATIONANALYTICS,OCF)'
        required: false

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      INPUT_CONTEXT: ${{ toJSON(github.event.inputs) }}
      var: ALATIONANALYTICS
    steps:
      - name: Dump input
        run: echo "$INPUT_CONTEXT"
      - name: Print values
        run: |        
          echo ${{ env.INPUT_CONTEXT.ALATIONANALYTICS }}
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github).event.inputs }}
      #   run: echo "$GITHUB_CONTEXT"
      # - name: Print values
      #   run: |
      #     echo $GITHUB_CONTEXT.ALATIONANALYTICS
      # - name: Dump job context
      #   env:
      #     JOB_CONTEXT: ${{ toJSON(job) }}
      #   run: echo "$JOB_CONTEXT"
      # - name: Dump steps context
      #   env:
      #     STEPS_CONTEXT: ${{ toJSON(steps) }}
      #   run: echo "$STEPS_CONTEXT"
      # - name: Dump runner context
      #   env:
      #     RUNNER_CONTEXT: ${{ toJSON(runner) }}
      #   run: echo "$RUNNER_CONTEXT"
      # - name: Dump strategy context
      #   env:
      #     STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      #   run: echo "$STRATEGY_CONTEXT"
      # - name: Dump matrix context
      #   env:
      #     MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      #   run: echo "$MATRIX_CONTEXT"
