name: 'Delete Instance'

on:
  # push:
  #   branches:
  #   - main
  # pull_request:

  workflow_dispatch:
    inputs:
        WORKFLOW_RUN:
          description: 'Workflow run to delete'
          required: true
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ami: [ami-0443305dabd4be2bc, ami-0ba62214afa52bec7]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TFSTATE_FILE: ${{ github.event.inputs.WORKFLOW_RUN }}/terraform.tfstate
      TERRAFORM_STRING: '-var="image_id=${{ matrix.ami }}"
        -var="alation_version=alation-k8s-master-20210729.30"
        -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}"
        -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        -var="instanceName=alation-test-k8s-$GITHUB_RUN_NUMBER-${{ matrix.ami }}"
        '

    defaults:
      run:
        shell: bash
        working-directory: .github/terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_S3_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Copy key from S3 bucket
      run: |
        aws s3 cp s3://gh-action-tf-state/gh-actions-terraform.pem ~/.ssh/gh-actions-terraform.pem

    - name: Terraform Init
      run: terraform init -backend-config="key=$GITHUB_RUN_NUMBER/${{ matrix.ami }}/terraform.tfstate"

    - name: Terraform Destroy
      run: terraform destroy -auto-approve ${{ env.TERRAFORM_STRING }}

    - name: Remove terraform state from S3
      if: ${{ success() }}
      run: aws s3 rm s3://gh-action-tf-state/${{ env.TFSTATE_FILE }}
