# This is a basic workflow to help you get started with Actions

name: unified-build-staged

# Controls when the action will run. 
on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Log level'     
#         required: true
#         default: 'warning'
#       tags:
#         description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2
      - run: mkdir -p ./archive
      
      - name: Build and store docker tarball
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./installer
          push: false
          tags: alation/installer:latest
          outputs: type=docker,dest=./archive/out.tar

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: List of files
        run: ls -al ./archive

      - name: Temporarily save Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: ./archive
          retention-days: 1
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Download files from S3
        run: |
          mkdir -p archive
          aws s3 cp ${{ secrets.S3_BUCKET_URL }}aa-0.1.0.tgz ./archive
          aws s3 cp ${{ secrets.S3_BUCKET_URL }}ocf-0.1.0.tgz ./archive
          ls -al ./archive
    
      - name: Temporarily save downloaded files
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./archive
          retention-days: 1

  package:
    needs: [build, fetch]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: ./archive1
      
      - name: Retrieve saved downloads
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: ./archive2
      - name: Compress files
        run: tar -cvzf alation-0.1.0.tgz ./archive

      - name: Upload to final artifact to S3
        run: aws s3 cp alation-0.1.0.tgz ${{ secrets.S3_BUCKET_URL }}alation-0.1.0.tgz
