name: unified-installer-final

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      ALATION_ANALYTICS:
        description: 'Alation analytics version'
        required: false
      OCF:
        description: 'OCF version'
        required: false
      KURL:
        description: 'KURL Version'
        required: false

env:
  S3_DEV_BUCKET_URL: "s3://${{ secrets.S3_DEV_BUCKET_NAME }}"
  S3_RELEASE_BUCKET_URL: "s3://${{ secrets.S3_RELEASE_BUCKET_NAME }}"
  BASE_DIR: ./alation
  RESOURCE_DIR: ./alation/res
  MODULES_DIR: ./alation/res/modules
  KURL_PATCH_DIR: ./alation/res/kurl_patch
  ALATION_OUTPUT: alation-$GITHUB_RUN_NUMBER.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build installer binary
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./installer
          push: false
          tags: alation/installer:latest
          outputs: type=docker,dest=installer.tar.gz
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: List of files
        run: find ${{ env.BASE_DIR }}

      - name: Temporarily save Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: ${{ env.BASE_DIR }}
          retention-days: 1

  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
              
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}

      - name: Read environment versions files
        id: read_env
        run: |
          applicationList=()
          for i in ./versions/*.sh; do
            while read line || [ -n "$line" ];
            do
                set -f; IFS="="; application=($line)
                applicationList+=(${application[0]})
            done < "${i}"
            cat "$i"
            echo
          done  >> $GITHUB_ENV
          # echo APPLICATION_LIST=${applicationList[@]} >> $GITHUB_ENV
          echo ::set-output name=applicationList::${applicationList[@]}

      - name: Set environment variables
        run: |
          echo KURL_FILE_NAME=kurl-${{ env.KURL }}.tar.gz >> $GITHUB_ENV
      - name: Creating required directories
        run: |
          mkdir -p ${{ env.BASE_DIR }}
          mkdir -p ${{ env.MODULES_DIR }}
          mkdir -p ${{ env.KURL_PATCH_DIR }}


      - name: Download files from S3
        run: |
          for i in ${{ steps.read_env.outputs.applicationList }}; do
            echo $i
          done

      - name: Copy res content from source code to archiving directory
        run: |
          cp -a ${{ github.workspace }}/installer/res/. ${{ env.BASE_DIR }}/res/

      - name: Download files from S3
        run: |
          for i in ${{ steps.read_env.outputs.applicationList }}; do
            applicationName="${i,,}"
            application="${applicationName}-${!i}.tar.gz"
            echo "$applicationName and version $applicationTag"            
            aws s3 cp ${{ env.S3_DEV_BUCKET_URL }}/$application ${{env.MODULES_DIR}}/$applicationName/
          done

      - name: Print list files
        run: find .
      
      - name: Temporarily save downloaded files
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ env.BASE_DIR }}
          retention-days: 1

  package:
    needs: [build, download]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: ${{ env.BASE_DIR }}
      
      - name: Retrieve saved downloads
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: ${{ env.BASE_DIR }}

      - name: Print list files
        run: find .