# This is a basic workflow to help you get started with Actions

name: unified-build

# Controls when the action will run. 
on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ALATION_ANALYTICS:
        description: 'Alation Analytics version'
        required: false
      OCF:
        description: 'OCF version'
        required: false


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICES: ("ALATION_ANALYTICS"  "OCF") >> $GITHUB_ENV
    steps:
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2
      
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2
      # - name: Run environment versions files
      #   run: |
      #     for f in ${{ github.workspace }}/versions/*.sh; do
      #       cat "$f"
      #       echo
      #     done >> $GITHUB_ENV

      # - name: Run environment versions files
      #   id: data
      #   run: |
      #     echo ::set-output name=data::$(for f in ${{ github.workspace }}/versions/*.sh; do
      #       cat "$f"
      #       echo
      #     done)
      # - name: Print output
      #   run: echo ${{ steps.data.outputs.data}}


      - name: Split string
        run: |
          for i in ./versions/*.sh; do
            while read line || [ -n "$line" ];
            do
              echo $line
            done < "${i}"
          done >> $GITHUB_ENV
      - name: Print environment variables
        run: echo $OCF          
      
      - name: Print environment variables
        run: echo ${{ env.OCF }} ${{ env.ALATION_ANALYTICS }}
      
      - name: Services vars
        run: echo "${{ env[env.SERVICES[0] }}"

      # - name: Download files from S3
      #   run: |
      #     mkdir -p archive
      #     aws s3 cp ${{ secrets.S3_BUCKET_URL }}aa-0.1.0.tgz ./archive
      #     aws s3 cp ${{ secrets.S3_BUCKET_URL }}ocf-0.1.0.tgz ./archive
      #     ls -al ./archive

      # - name: Build and store docker tarball
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./installer
      #     push: false
      #     tags: alation/installer:latest
      #     outputs: type=docker,dest=./archive/out.tar

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

      # - name: List of files
      #   run: ls -al ./archive

      # - name: Compress files
      #   run: tar -cvzf alation-0.3.0.tgz ./archive

      # - name: Upload to final artifact to S3
      #   run: aws s3 cp alation-0.3.0.tgz ${{ secrets.S3_BUCKET_URL }}alation-0.3.0.tgz
#       - name: Create zip
#         uses: ihiroky/archive-action@v1
#         with:
#           root_dir: path_to_arhive_root_directory
#           file_path: path_to_archive.zip
