name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: ${{github.workspace}}/installer          
          skip-go-installation: false # Optional: if set to true then the action will use pre-installed Go.
