name: Publish Docker images

on:
  workflow_dispatch:
    inputs:
      ALATION_VERSION:
        description: "Alation Build version"
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ECR_SRC_ACCESS_KEY_ID: ${{ secrets.ECR_SRC_ACCESS_KEY_ID }}
      ECR_SRC_SECRET_ACCESS_KEY: ${{ secrets.ECR_SRC_SECRET_ACCESS_KEY }}
      ECR_DEST_ACCESS_KEY_ID: ${{ secrets.ECR_DEST_ACCESS_KEY_ID }}
      ECR_DEST_SECRET_ACCESS_KEY: ${{ secrets.ECR_DEST_SECRET_ACCESS_KEY }}
      SRC_ECR_URL: 248135293344.dkr.ecr.us-east-2.amazonaws.com
      DEST_ECR_URL: 118618885326.dkr.ecr.us-east-2.amazonaws.com
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.ECR_SRC_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.ECR_SRC_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr1
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.ECR_DEST_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.ECR_DEST_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr2
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull docker images
        run: |
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alationfc:11.2.3-159997
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/acm:0.1.0-108
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/aim:0.1.0-108
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/containerd:0.1.0-108
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/aamanager:1.16.0-1739233829
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/postgres:1.16.0-1739233829
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/base-transform:1.16.0-1739233829
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/install-hook:1.16.0-1739233829
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/rabbitmq:1.16.0-1739233829
      - name: Tag docker images
        run: |
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alationfc:11.2.3-159997 118618885326.dkr.ecr.us-east-2.amazonaws.com/alationfc:11.2.3-159997
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/acm:0.1.0-108 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/acm:0.1.0-108
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/aim:0.1.0-108 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/aim:0.1.0-108
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/containerd:0.1.0-108 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/containerd:0.1.0-108
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/aamanager:1.16.0-1739233829 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/aamanager:1.16.0-1739233829
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/postgres:1.16.0-1739233829 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/postgres:1.16.0-1739233829
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/base-transform:1.16.0-1739233829 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/base-transform:1.16.0-1739233829
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/install-hook:1.16.0-1739233829 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/install-hook:1.16.0-1739233829
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/rabbitmq:1.16.0-1739233829 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/rabbitmq:1.16.0-1739233829

      - name: Publish docker images
        run: |
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alationfc:11.2.3-159997
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/acm:0.1.0-108
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/aim:0.1.0-108
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/containerd:0.1.0-108
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/aamanager:1.16.0-1739233829
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/postgres:1.16.0-1739233829
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/base-transform:1.16.0-1739233829
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/install-hook:1.16.0-1739233829
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/rabbitmq:1.16.0-1739233829

      # - name: Push, tag and pull images
      #   run: |
      #     array=(model-server/sentence-bert-encoder:0.2.0-1830545655 \
      #     model-server/universal-sentence-encoder:0.2.0-1830545655 \
      #     model-server:0.2.0-1830545655)

      #     for image in “${array[@]}”
      #     do
      #       echo "*********[$image]: Processing started*********"
      #       echo "[$image]: Pulling image from source ECR repo"
      #       echo ${{ env.SRC_ECR_URL }}/$image
      #       docker pull ${{ env.SRC_ECR_URL }}/$image
      #       echo "[$image]: Tagging image with destination ECR repo"
      #       docker tag ${{ env.SRC_ECR_URL }}/$image ${{ env.DEST_ECR_URL }}/$image
      #       echo "[$image]: Pushing image to destination ECR repo"
      #       docker push ${{ env.DEST_ECR_URL }}/$image
      #       echo "*********[$image]: Processing completed*********\n\n"
      #     done
