name: Publish Docker images

on:
  workflow_dispatch:
    inputs:
      ALATION_VERSION:
        description: "Alation Build version"
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ECR_SRC_ACCESS_KEY_ID: ${{ secrets.ECR_SRC_ACCESS_KEY_ID }}
      ECR_SRC_SECRET_ACCESS_KEY: ${{ secrets.ECR_SRC_SECRET_ACCESS_KEY }}
      ECR_DEST_ACCESS_KEY_ID: ${{ secrets.ECR_DEST_ACCESS_KEY_ID }}
      ECR_DEST_SECRET_ACCESS_KEY: ${{ secrets.ECR_DEST_SECRET_ACCESS_KEY }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.ECR_SRC_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.ECR_SRC_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr1
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.ECR_DEST_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.ECR_DEST_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr2
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull docker images
        run: |
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/acm:0.1.0-126.production-alation-2021.4
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/aim:0.1.0-126.production-alation-2021.4
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/containerd:0.1.0-126.production-alation-2021.4
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/aamanager:1.14.0-1495867875
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/base-transform:1.14.0-1495867875
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/install-hook:1.14.0-1495867875
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/postgres:1.14.0-1495867875
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/rabbitmq:1.14.0-1495867875
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alationfc:10.2.8-158918
          docker pull 248135293344.dkr.ecr.us-east-2.amazonaws.com/alationfc:10.2.8-158918
      - name: Tag docker images
        run: |
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/acm:0.1.0-126.production-alation-2021.4   118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/acm:0.1.0-126.production-alation-2021.4
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/aim:0.1.0-126.production-alation-2021.4  118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/aim:0.1.0-126.production-alation-2021.4
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/ocf-system/containerd:0.1.0-126.production-alation-2021.4 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/containerd:0.1.0-126.production-alation-2021.4
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/aamanager:1.14.0-1495867875 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/aamanager:1.14.0-1495867875
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/base-transform:1.14.0-1495867875 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/base-transform:1.14.0-1495867875
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/install-hook:1.14.0-1495867875 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/install-hook:1.14.0-1495867875
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/postgres:1.14.0-1495867875 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/postgres:1.14.0-1495867875
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/rabbitmq:1.14.0-1495867875 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/rabbitmq:1.14.0-1495867875
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alationfc:10.2.8-158918 118618885326.dkr.ecr.us-east-2.amazonaws.com/alationfc:10.2.8-158918
          docker tag 248135293344.dkr.ecr.us-east-2.amazonaws.com/alationfc:10.2.8-158918 118618885326.dkr.ecr.us-east-2.amazonaws.com/alationfc:10.2.8-158918
      - name: Publish docker images
        run: |
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/acm:0.1.0-126.production-alation-2021.4
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/aim:0.1.0-126.production-alation-2021.4
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/ocf-system/containerd:0.1.0-126.production-alation-2021.4
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/aamanager:1.14.0-1495867875
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/base-transform:1.14.0-1495867875
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/install-hook:1.14.0-1495867875
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/postgres:1.14.0-1495867875
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alation-analytics/rabbitmq:1.14.0-1495867875
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alationfc:10.2.8-158918
          docker push 118618885326.dkr.ecr.us-east-2.amazonaws.com/alationfc:10.2.8-158918
