name: Release-new

on:
  workflow_dispatch:
    inputs:
      ALATION_VERSION:
        description: "Alation Build version"
        required: true
jobs:
  upload-and-tag:
    runs-on: ubuntu-latest
    env:
      ALATION_VERSION: ${{ github.event.inputs.ALATION_VERSION }}
      ALATION_BUILD: ${{ github.event.inputs.ALATION_VERSION }}.tar.gz
    steps:
      - name: Configure AWS Credentials for Engineering account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}

      - name: Get Alation installer
        run: |
          major=`echo ${{ env.ALATION_VERSION }} | cut -d. -f1` >> $GITHUB_ENV
          minor=`echo ${{ env.ALATION_VERSION }} | cut -d. -f2` >> $GITHUB_ENV
          patch=`echo ${{ env.ALATION_VERSION }} | cut -d. -f3` >> $GITHUB_ENV
          build=`echo ${{ env.ALATION_VERSION }} | cut -d. -f4` >> $GITHUB_ENV
          printenv
          aws s3 cp ${{ env.S3_RELEASE_BUCKET_URL }}/$major/${{ env.minor }}/$patch/$build/${{ env.ALATION_BUILD }} .

      - name: Extract the build
        run: |
          tar -xvzf ${{ env.ALATION_BUILD }}

      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_S3_REGION }}

      # - name: Upload build to production S3 bucket
      #   run: |
      #     aws s3 cp ${{ env.ALATION_BUILD }} ${{ env.S3_PROD_RELEASE_BUCKET_URL }}/$major/$minor/$patch/$build/${{ env.ALATION_BUILD }}

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.unified-installer-build.outputs.alation-version }}
          body: ${{ needs.unified-installer-build.outputs.module-versions }}
          bodyFile: ${{ env.ALATION_VERSION }}/versions.txt
