name: Releases

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional Tag"
        required: false
  workflow_run:
    workflows: ["unified-installer-build-pipeline"]
    type:
      - complete
jobs:
  unified-installer-build:
    uses: sureshappana-alation/alation_installer/.github/workflows/unified-installer-build-pipeline.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
  tag:
    runs-on: ubuntu-latest
    needs: unified-installer-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print list of files
        run: |
          echo "List of files"
          find .
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.unified-installer-build.outputs.version }}
          body: ${{ needs.unified-installer-build.outputs.modules }}
