name: Releases

on: 
  push:
    tags:
    - '*'
  workflow_dispatch:    
    inputs:
      tag:
        description: "Optional Tag"
        required: false
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.tag }}
#        artifacts: "release.tar.gz,foo/*.txt"
#        bodyFile: "body.md"
#        token: ${{ secrets.GITHUB_TOKEN }}
