name: "Setup ACS instance (Eksctl + unified installer)"

on:
  workflow_dispatch:
    inputs:
      # ALATION_VERSION:
      #   description: "Alation build version to install"
      #   required: true
      EKS_CLUSTER_NAME:
        description: "EKS Cluster Name"
        required: true
      EXISTING_CLUSTER:
        description: "Setup Alation on Existing Cluster (valid values: Yes or No). Default: creates the cluster first"
        required: false
        default: "No"
jobs:
  terraform:
    name: "setup"
    runs-on: ubuntu-latest
    env:
      DATADOG_DATADOG_APIKEY: ${{ secrets.DATADOG_DATADOG_APIKEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}

      - name: Setup helm
        uses: azure/setup-helm@v1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1

      - name: Eksctl setup
        if: ${{ github.event.inputs.EXISTING_CLUSTER == 'No' }}
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.67.0/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version

      - name: Generate eksctl config file
        if: ${{ github.event.inputs.EXISTING_CLUSTER == 'No' }}
        run: |
          export  CLUSTERNAME=${{ github.event.inputs.EKS_CLUSTER_NAME }}
          envsubst < ${{ github.workspace }}/.github/templates/eksctl-config.yaml.tmpl > ${{ github.workspace }}/.github/templates/eksctl-config.yaml
          cat ${{ github.workspace }}/.github/templates/eksctl-config.yaml

      - name: Create cluster
        if: ${{ github.event.inputs.EXISTING_CLUSTER == 'No' }}
        run: |
          eksctl create cluster -f ${{ github.workspace }}/.github/templates/eksctl-config.yaml

      - name: Get kubectx
        if: ${{ github.event.inputs.EXISTING_CLUSTER != 'No' }}
        run: aws eks --region us-east-2 update-kubeconfig --name ${{ github.event.inputs.EKS_CLUSTER_NAME }}

      - name: Get Alation installer
        run: |
          aws s3 cp s3://unified-installer-build-pipeline-release/1/0/0/137/1.0.0.137_updated.tar.gz .
          tar -xvzf 1.0.0.137_updated.tar.gz
          cd 1.0.0.137
          chmod +x installer
          ./installer -platform=eks

      - name: Run the configure scripts
        run: |
          chmod +x ${{ github.workspace }}/.github/scripts/alationconf_setup.sh
          ${{ github.workspace }}/.github/scripts/alationconf_setup.sh

      - name: Catalog URL
        run: kubectl get svc -l app.kubernetes.io/name=alationfc -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}'
